--- 
title: "2019年全国应急救援、生产安全事故各十大典型案例"
author: "中华人民共和国应急管理部"
date: "2021-01-11"
output:
  word_document: default
  pdf_document: default
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
colorlinks: yes
lot: yes
lof: yes
geometry:
- b5paper
- tmargin=2.5cm
- bmargin=2.5cm
- lmargin=3.5cm
- rmargin=2.5cm
site: bookdown::bookdown_site
description: 一个简单的中文书示例。
github-repo: yihui/bookdown-chinese
documentclass: ctexbook
---

```{r setup, include=FALSE}
options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 55, digits = 4
)

# 填上你需要用到的包，如 c('ggplot2', 'dplyr')
lapply(c('tidyverse','readxl'), function(pkg) {
  if (system.file(package = pkg) == '') install.packages(pkg)
})
```

2019年是应急管理部门组建到位后全面履职的第一年，也是各类灾害事故风险挑战明显上升的一年。在以习近平同志为核心的党中央坚强领导下，应急管理部坚持以习近平新时代中国特色社会主义思想为指导，认真贯彻党中央、国务院各项决策部署，坚持以改革为动力、以关键带全局，狠抓重大安全风险防控，系统推进应急管理事业创新发展。应急管理体制已经明确，工作机制基本形成，力量体系初步建立，应急救援能力和效率显著提高，应急管理科学化、专业化、智能化、精细化水平不断提升，我国应急管理体制机制在实践中充分展现出自己的特色和优势。在各级党委政府坚强领导下和各部门各单位共同努力下，全国安全形势保持平稳，生产安全事故总量、较大事故和重特大事故保持“三个下降”，自然灾害因灾死亡失踪人数、倒塌房屋数量、直接经济损失占GDP比重较近5年均值大幅降低，有效应对了一系列重特大灾害事故，最大限度减少了人员伤亡和财产损失。

日前，应急管理部会同国务院安委会办公室、国家减灾委办公室对2019年各类突发灾害事故案例进行梳理，公布了应急救援、生产安全事故各十大典型案例，认真总结应急救援和现场处置的成功经验，督促各地各部门认真吸取各类灾害事故教训，提升全社会应急意识、安全意识和责任意识，筑牢防灾减灾救灾的人民防线。

# 2019年全国应急救援十大典型案例

## 福建福州“2·16”建筑坍塌事故救援

2019年2月16日5时50分许，福州市仓山区叶下村一民房坍塌，造成17人被困。应急管理部门启动应急响应，指导调度救援工作。福建省应急管理厅和消防救援总队调派5支地震抢险救援专业队、2支搜救犬分队共52辆消防车、285名指战员、9头搜救犬到场处置，福州市政府启动重大灾害事故应急响应机制，成立现场指挥部，调集公安、市政、医疗救护等力量赶赴现场协同处置，先后从废墟中打通11条救援通道，经过近16小时持续救援，搜救出全部17名被困人员，其中14人生还。

**主要经验:**发挥地质（地震）抢险救援专业队拳头作用，第一时间成建制、模块化调集消防救援专业人员和装备以及搜救犬到场实施救援。运用先进科技成果，会同公安部门快速精准确定被困者位置。社会应急力量协同救援，在搜救被埋压人员过程中，医疗救护部门及时为其提供生命支持，极大提高了被埋压人员生还率。

## 山西乡宁“3·15”山体滑坡抢险救援

2019年3月15日18时10分许，山西省临汾市乡宁县枣岭乡发生山体滑坡，造成一些建筑被冲垮、33人被埋压。应急管理部持续调度，派出部领导带队的工作组赴现场指导处置，山西省政府启动重大灾害事故应急响应预案，成立现场指挥部，消防救援、公安、自然资源、医疗救护等部门和当地驻军、武警和社会应急力量第一时间赶到现场开展救援，省应急管理厅和消防救援总队共调集524名指战员、18头搜救犬和千余套救援装备投入救援工作。经过138小时艰苦奋战，将33名被困人员全部救出，其中13人生还。

**主要经验:**迅速启动重大灾害事故应急响应机制，第一时间调集各有关力量到场，实施全方位有力有效救援。针对山体滑坡范围广、体量大以及地质结构不稳定特点，科学评估现场灾情，划定被埋人员搜救作业区域，利用搜救犬与侦测仪器相结合、人工搜救与工程机械相结合，抢救出全部遇险人员。

## 江苏响水天嘉宜化工有限公司“3·21”特别重大爆炸事故救援

2019年3月21日14时48分，位于江苏省盐城市响水县生态化工园区的天嘉宜化工有限公司发生特别重大爆炸事故，造成78人死亡、76人重伤，640人住院治疗，直接经济损失198635.07万元。事故发生后，应急管理部会同江苏省启动特别重大事故应急响应，成立现场指挥部。消防救援队伍930名指战员、200余辆救援车辆、20台大型工程机械火速赶赴现场，第一时间深入核心区，针对大量人员被困废墟的情况，抢抓72小时黄金救援期，开展“地毯式、全覆盖、全时段”排查搜救，全力营救被困人员，同时进行8处火灾扑救。经过80多个小时连续奋战，7轮不间断搜救，在爆炸核心区搜救出遇险人员164人（其中86人生还），累计监护输转近百种、10万余吨危化品。

**主要经验:**党中央、国务院高度重视，当地党委政府统一领导，充分发挥体制优势，消防、应急、公安、环保、卫生、军队武警等各方力量全力以赴形成合力，指挥团队专业果断，采取措施科学稳妥，特别是抢险救援人员不怕牺牲、英勇善战，现场救援、防控污染、抢救伤员、维护稳定等专项工作尽职到位，最大程度降低了事故危害和规模。

## 山西沁源“3·29”森林火灾扑救

2019年3月29日13时许，山西省沁源县王陶乡王陶村因养鸡场架空铝绞线碰撞打火引发森林火灾，受害森林面积约942公顷，威胁附近6个乡（镇）39个行政村51个自然村18家企业2.47万人。此次扑救共投入森林消防、解放军、武警官兵、消防和专业队伍等救援力量约1.5万人，调集飞机14架、消防车辆、挖掘机等大型机械280余台。按照撤、封、控、扑、清的原则，及时转移安置群众9000余人，实施交通管控和空中侦察、地面巡防，快速打通8公里长防火隔离带，综合利用化学灭火、航空灭火、工程灭火、人工作业等多种技术手段打歼灭战，跟进开展余火清理，强化后勤保障，经过7昼夜连续奋战，明火于4月5日10时30分全部扑灭，避免了人员伤亡和次生灾害发生。

**主要经验:**一是快速响应重兵投入。山西省第一时间启动省级森林火灾应急预案，成立前线指挥部，省、市、县各级党委政府主要领导靠前指挥。应急管理部持续跟踪调度，根据火场态势主动增派森林消防局4个总队级单位和航空救援力量支援扑救，充分发挥了国家队、主力军作用。二是科学指挥战法灵活。参战队伍围绕“先封控、再消灭”总体作战目标，准确研判火场态势，科学制定扑火作战方案，细化任务分工，采取“多点突破、分段歼灭”“强攻推进、递进超越”等战术，组织全部力量进行扑打。三是密切协同扑救高效。这次作战力量多元化特点突出，既有森林消防队伍和驻地部队官兵，也有航空救援力量和地方扑火队员，国家力量与地方扑火队员协同作战、空地一体，各司其职，各尽其能，提高了综合作战能力。

## 上海长宁“5·16”建筑坍塌事故救援

2019年5月16日11时17分许，上海市长宁区昭化路148号光之里二期改造建筑工程发生坍塌，造成25人被埋压。上海市应急管理局和消防救援总队接到报警后，立即调集41辆消防车、300余名指战员、8头搜救犬和10台工程机械赶赴现场救援。同时，应急管理部门启动应急联动机制，协调公安、住建、医疗救护等力量到场协同处置。伴随着坍塌建筑局部结构严重变形，随时可能发生再次坍塌的危险情况，救援人员果断采取“询情与检测同步、搜索与救助并行”的救援方案，将坍塌现场划分为4个作业区域，实施交叉搜救。在14个小时内搜救出25名被埋压人员，其中13人生还。

**主要经验:**迅速启动应急响应机制，第一时间协调各有关力量到场实施救援。针对坍塌建筑变形严重、情况复杂且随时可能发生再次坍塌的危险，组织建筑结构等专家科学评估现场灾情，划片搜救、开辟通道，机械与人工救援相结合，为短时间成功处置创造了条件。

## 西百色“5·20”建筑坍塌事故救援

2019年5月20日0时许，百色市右江区东州大道0776酒吧发生楼顶坍塌事故，造成60余人被困。应急管理部持续调度救援处置，应急管理部、卫健委、住建部组织专家赶赴现场指导救援。广西自治区应急管理厅和消防救援总队接警后，立即调集5支地震抢险救援专业队共245名指战员、7头搜救犬赶赴现场救援，打通6条救援通道，5个小时内共搜救出60名遇险人员，且全部生还。之后经过34个小时连续作战，将被深度埋压的9名遇险人员全部救出，其中6人遇难。

**主要经验:**准确根据建筑物使用性质和事故发生时间，迅速协调专业力量和设施到场实施救援。科学评估现场灾情和被困人员状况，迅速组织力量多途径打开救生通道，为抢救疏散人员赢得了宝贵时间。

## 江西宜春“7·21”山洪遇险“驴友”救援

2019年7月21日14时许，江西省宜春市靖安县吕阳洞山区突降暴雨引发山洪，造成283名“驴友”遇险被困。险情发生后，应急管理部开展调度指导，江西省应急管理厅和消防救援总队启动应急响应预案，调集100余名指战员和搜救犬、无人机、水域救援等装备，赶赴现场营救被困人员。救援过程中，救援人员37批次进山搜救、12次冒险搭建水上生命通道，采取无人机巡航定位、绳索搭桥、挖掘机接应等救援方式，搜救出全部被困“驴友”。

**主要经验:**迅速启动应急响应机制，实施“大面积、大区域”救援。针对地形地貌复杂以及遇险人员相对分散特点，利用手机信号定位、无人机空中侦察等技术手段，确定遇险人员准确位置，爬山涉水、分区搜索，架设人工绳桥和运用重型工程机械营救遇险人员。社会应急力量参与救援行动，野外作业经验丰富，是一支重要的救援协同辅助力量。

## 四川龙潭水电站险情处置

2019年8月20日，四川省阿坝州普降大到暴雨，强降雨导致岷江支流渔子溪爆发特大山洪泥石流，灾害造成龙潭水电站大坝电源中断，泄洪闸未全部开启，发生漫坝险情。大坝上游119名群众一度被困，同时坝体面临失稳溃决风险，严重威胁下游约5000人生命安全。险情发生后，应急管理部启动应急响应，第一时间派出工作组赶赴现场，14天全过程指导督导处置。当地党委政府立即转移下游受威胁群众，同时积极组织营救上游被困人员，一方面利用直升机转运伤员，另一方面全力打通救援道路，至8月23日全部被困人员获救。为彻底排除险情，现场指挥部科学制定3套提闸方案以及爆破和开槽导流除险方案，组织做好险情处置。应急管理部门积极协调各方力量，开展抢险救援；安能集团克服困难迅速打通上坝道路；国家能源集团搭建2座应急交通桥，组织突击队伍上坝除险，先后组织7次提闸，细化闸门破拆准备；水利、气象部门全程提供监测预报信息；交通、通讯部门全力确保道路、通讯畅通；国资委、能源部门重点督导水电站业主除险进程。经多方共同努力，9月3日，2号闸门爆破破拆成功，水位迅速降至坝顶以下，龙潭水电站险情解除。

**主要经验:**龙潭水电站险情的成功处置，主要得益于统一领导、权责一致、权威高效、上下联动的国家应急能力体系的建立，各部门在统一的指挥体系下密切配合，克服安全风险巨大、施工环境复杂、救援条件恶劣等困难，全力做好抢险救援工作，整个抢险救援过程有力有序有效。

## 辽宁沈阳“12·2”高层建筑火灾扑救

2019年12月2日21时16分许，辽宁省沈阳市浑南新区SR新城102号楼A座发生火灾，大量人员被困。辽宁省应急管理厅和消防救援总队接警后，迅速调派98辆消防车、400余名指战员到场处置。应急管理部门协调公安、卫健、住建等部门以及供电、供水、燃气等应急力量到场协同处置。因火势向上蔓延迅速，楼内居民生命安全受到严重威胁，救援人员组织内攻小组深入建筑内部，分段逐层疏散楼内遇险居民，同时铺设供水线路，内外结合全力控制火势发展蔓延。经过2个小时艰苦奋战，成功扑灭大火，并在公安部门和物业单位配合下，搜救和疏散出284名居民，无人员伤亡。

**主要经验:**发挥高层建筑灭火救援专业队的尖刀作用，根据高层建筑战斗编成和展开程序，到场后快速实施灭火救援行动。针对高层建筑火灾因“烟囱效应”极易发生跳跃式或立体式燃烧，及时组织力量分层疏散人员、排烟散热、设防堵截，全力控制火势向上层发展蔓延，在较短时间内有效扑灭了火灾。

## 川煤集团杉木树煤矿“12·14”透水事故救援

2019年12月14日15时26分，四川芙蓉集团实业有限责任公司杉木树煤矿发生透水事故，造成18人被困井下。应急管理部立即启动应急响应，派出部领导带队的工作组赴现场指导救援。省、市党委政府迅速成立现场指挥部，调集专业救护队、排水队伍共13支、256人实施救援。现场采取导流、分流和抽排等措施降低井下水位上涨对被困人员的威胁，利用井下压风管道输送压缩空气保障被困区域氧气充足，实时监测抽排瓦斯，地面安设钻机向人员被困区域巷道打钻，对巷道进行清淤、搜救13名被困人员。18日3时38分，13名被困人员全部脱离被困巷道，至7时56分，经过连续88小时的全力施救，13人全部安全升井并送医救治。

**主要经验:**方案科学合理、现场指挥坚强得力。现场指挥部组织制定了科学、合理、有针对性的救援方案和安全技术保障措施，救援工作围绕加强排水、瓦斯排放、巷道清理以及安全防护等工作展开，确保了科学救援、安全救援、快速救援。救援资源统一调度、救援队伍协同作战。合理调配专业排水队伍、矿山救援队伍、工程施工队伍及大型排水设备、局部通风设备、保障供电设备等应急资源，实现了统一指挥、高效运转。

# 2019年全国十大生产安全事故

## 江苏响水天嘉宜化工有限公司“3·21”特别重大爆炸事故

### 事故概况

2019年3月21日14时48分，位于江苏省盐城市响水县生态化工园区的天嘉宜化工有限公司发生特别重大爆炸事故，造成78人死亡、76人重伤，640人住院治疗，直接经济损失198635.07万元。发生原因是，事故企业旧固废库内长期违法贮存的硝化废料（主要成分是二硝基二酚、三硝基一酚、间二硝基苯、水和少量盐分等）持续积热升温导致自燃，燃烧引发爆炸。

### 主要教训

**一是事故企业安全意识、法律意识淡漠。**天嘉宜公司无视国家环境保护和安全生产法律法规，长期刻意瞒报、违法贮存、违法处置硝化废料，安全管理混乱。

**二是中介机构弄虚作假。**有关环保评价机构出具虚假失实文件，导致事故企业硝化废料重大风险和事故隐患未能及时暴露，干扰误导了有关部门的监管工作。

**三是江苏省各级政府有关部门监管责任履行不到位。**应急管理部门履行安全生产综合监管职责不到位，生态环境部门未认真履行危险废物监管职责，工信、市场监管、规划、住建和消防等部门也不同程度存在违规行为。

**四是响水县和生态化工园区安全发展理念不牢。**重发展轻安全，招商引资安全环保把关不严，对天嘉宜公司长期存在的重大风险隐患视而不见，复产把关流于形式。

**五是江苏省、盐城市未认真落实地方党政领导干部安全生产责任制，重大安全风险排查管控不全面、不深入、不扎实。**

## 长深高速江苏无锡“9・28”特别重大道路交通事故

### 事故概况

2019年9月28日，长深高速公路江苏无锡段发生一起大客车碰撞重型货车的特别重大道路交通事故，造成36人死亡、36人受伤。发生原因是，事故大客车在行驶过程中左前轮爆胎，导致车辆失控与中央隔离护栏碰撞，冲入对向车道，与对向大货车相撞。大客车上大部分乘员未系安全带，在事故发生时脱离座椅，加重了事故伤亡后果。

### 主要教训

道路客运行业跨省异地源头管控存在漏洞。

一是企业注册地有关部门对未取得道路运输经营许可的企业、车辆监管不力，对企业日常安全管理严重缺失的问题失察失管，未及时处理其他部门和外地关于事故企业及车辆涉嫌非法营运的抄告线索，没有真正形成监管合力和闭环管理

。二是车辆实际运营地有关部门未对非法营运大客车和非法组客点进行有效查处，仅将已掌握的异地籍非法车辆线索抄告车籍所在地交通运管部门。

三是有关部门未形成工作合力，车辆登记和营运准入联动机制不健全，车辆行驶证使用性质与运输许可情况不符；行业监管部门未有效利用部门协同监管平台加强“先照后证”改革后道路客运市场监管。

## 内蒙古自治区锡林郭勒盟西乌珠穆沁旗银漫矿业有限责任公司“2·23”井下车辆伤害重大生产安全事故

### 事故概况

2019年2月23日，内蒙古自治区西乌珠穆沁旗银漫矿业有限责任公司发生井下车辆伤害重大生产安全事故，造成22人死亡，28人受伤。发生原因是，外包工程施工单位违规使用未取得金属非金属矿山矿用产品安全标识、采用干式制动器的报废车辆向井下运送作业人员。事故车辆驾驶人不具备大型客运车辆驾驶资质，驾驶事故车辆在措施斜坡道向下行驶过程中，制动系统发生机械故障，制动时促动管路漏气，导致车辆制动性能显著下降。驾驶人遇制动不良突发状况处置不当，误操作将档位挂入三档，车辆失控引发事故。事故车辆私自改装车厢内座椅、未设置扶手及安全带，超员运输，加重了事故的损害后果。

### 主要教训

一是矿山企业安全生产主体责任长期悬空，对承包单位以包代管、包而不管，对其长期使用非法改装车辆运人、严重超载、人货混装等突出问题不检查、不制止。

二是外包工程施工单位严重违法违规，变相出卖资质，对分公司或项目部只收取管理费，不行使任何管理职责，其所属分公司或项目部人员东拼西凑，设备设施陈旧简陋。

三是地方有关部门监管不到位，对企业不按设计生产、违规违章作业等执法不严，对企业以包代管、包而不管等监督不力。

## 山东济南齐鲁天和惠世制药有限公司“4·15”重大着火中毒事故

### 事故概况

2019年4月15日，位于山东济南市历城区董家镇的齐鲁天和惠世制药有限公司四车间地下室，在冷媒系统管道改造过程中，发生重大着火中毒事故，造成10人死亡、12人受伤，直接经济损失1867万元。发生原因是，天和公司四车间地下室管道改造作业过程中，违规动火作业引燃现场堆放的冷媒增效剂（主要成份是为氧化剂亚硝酸钠，有机物苯并三氮唑、苯甲酸钠），瞬间产生爆燃，放出大量氮氧化物等有毒气体，造成现场施工和监护人员中毒窒息死亡。

### 主要教训

一是事故企业安全生产主体责任不落实。天和公司对动火作业风险辨识不认真，风险管控措施不落实；不了解冷媒增效剂的主要成分，对其危险特性及存在的安全风险认知不够；改造项目管理不严，外包施工队伍管理不到位，事故应急处置能力严重不足。

二是负责现场施工的承包商信邦公司对外派项目部管理严重缺失，对施工人员的教育培训不到位，现场施工人员严重违章。

三是冷媒增效剂的供应商光达公司非法生产、销售属于危险化学品的冷媒增效剂，未依法提供冷媒增效剂的安全技术说明书（SDS）。

四是山东省济南市及历城区党委政府有关部门、泰安市和肥城市有关部门未依法认真履行属地监管职责，特殊作业专项整治工作存在漏洞盲区，对天和公司等事故责任单位存在的违法违规问题失察。

## 河北衡水翡翠华庭“4·25”施工升降机轿厢坠落重大事故

### 事故概况

2019年4月25日，河北衡水市翡翠华庭项目1#楼建筑工地发生一起施工升降机轿厢（吊笼）坠落的重大事故，造成11人死亡、2人受伤，直接经济损失约1800万元。发生原因是，事故施工升降机在安装过程中，第16、17节标准节连接位置西侧的两条螺栓未安装，第17节以上的标准节不具有抵抗侧向倾翻的能力，形成重大事故隐患。但事故施工升降机安装完毕后，未按规定进行自检、调试、试运转，未组织验收即违规投入使用，最终导致事故发生。

### 主要教训

一是施工单位项目主要负责人系挂靠人员，实际上不在现场执业，施工现场以包代管，安全管理混乱。

二是专项施工方案内容不完整且与事故施工升降机机型不符，不能指导安装作业，安装前未按规定进行安全技术交底，安装过程中未安排专职安全员进行现场监督。

三是施工单位未组织验收即违规投入使用，在收到停止违规使用的监理通知后，仍不整改、继续使用。

四是政府及相关监管部门对施工现场存在的明显违法违规行为整治不力，安全监管流于形式。

## 河南三门峡河南省煤气（集团）有限责任公司义马气化厂“7·19”重大爆炸事故

### 事故概况

2019年7月19日，河南省三门峡市河南省煤气（集团）有限责任公司义马气化厂C套空分装置发生重大爆炸事故，共造成15人死亡，16人重伤，爆炸产生冲击波导致周围群众175人轻伤，直接经济损失8170.008万元。发生原因是，事故企业C套空分装置冷箱发生泄漏没有及时处置，富氧液体泄漏至珠光砂中，使碳钢冷箱构件发生低温脆裂，导致冷箱失稳坍塌，冷箱及铝质设备倒向东偏北方向，砸裂东侧500m3液氧贮槽，大量液氧迅速外泄到周边正在装车的液氧运输车辆发生第一次爆炸，随后铝质填料、筛板等在富氧环境下发生第二次爆炸。

### 主要教训

一是事故企业重生产轻安全，安全红线意识不强。不遵守企业技术操作规程，装置出现隐患没有及时处置；设备专业管理存在重大缺陷，备用空分设备管理不善，需要启用时无法启动；安全管理制度不落实，未按要求履行隐患排查责任。

二是河南省煤气（集团）有限责任公司安全生产主体责任落实不到位。停车检修制度不落实，未按规定督促义马气化厂及时停车检修，治理安全隐患。

三是河南能源化工集团有限公司安全意识不强，制度建设存在重大缺陷，安全管理存在重大漏洞。

四是三门峡市及义马市党委政府和有关部门属地安全监管责任落实不到位，督促事故企业开展防风险除隐患工作不力。

## 广西河池南丹庆达惜缘矿业投资有限公司“10·28”重大坍塌事故

### 事故概况

2019年10月28日，广西壮族自治区河池市南丹庆达惜缘矿业投资公司（以下简称庆达矿业公司）大坪村矿区锌银铅锑锡铜矿2号窿口内发生坍塌事故，造成13人死亡。发生原因是，庆达矿业公司在315米中段利用已封闭的废旧巷道，以及新开挖掘进的巷道到达445米水平，超出庆达公司采矿权范围1.3公里以上（平时设有密闭，以躲避监管部门检查）进入相邻矿山广西华锡集团铜坑矿已充填的采空区下方盗采边缘矿体。事故巷道靠近铜坑矿采空区冒落带。该区域上下都是铜坑矿的采空区和充填体，由于下部采空区发生垮塌，带动上部充填体和围岩发生垮落，产生冲击地压，导致人员受到冲击波伤害以及掩埋造成死亡。

### 主要教训

一是事故企业法制意识、安全意识淡薄，无视国家安全生产法律法规，无视矿工生命安全，对各级监管部门关于矿山安全生产要求置若罔闻，违法违规甚至非法生产。

二是地方有关部门监管执法不到位，对企业长期盗采资源等非法违法行为打击不力，执法不严。

三是地方政府安全发展理念不牢、安全生产红线意识不强，没有处理好安全与生产、安全与效益、安全与发展的关系，地方矿业秩序混乱。

## 山西晋中平遥峰岩煤焦集团二亩沟煤矿“11·18”重大瓦斯爆炸事故

### 事故概况

2019年11月18日,位于山西省晋中市平遥县的峰岩煤焦集团二亩沟煤矿发生重大瓦斯爆炸事故，造成15人死亡、9人受伤，直接经济损失2183.41万元。发生原因是，二亩沟煤矿违规布置炮采工作面开采区段煤柱、导通采空区，导致采空区瓦斯大量溢出；违章放炮产生明火引起瓦斯爆炸，波及到与之相邻的正规回采工作面。

### 主要教训 

一是煤矿主要负责人和技术负责人毫无“红线”意识，法律意识淡薄，故意违规开采保安煤柱。

二是通风管理混乱，两个采煤工作面之间违规串联通风。

三是违章放炮作业，放炮时炮眼不使用水泡泥封堵，不执行“一炮三检”和“三人连锁爆破”制度。

四是火工品管理混乱，刻意隐瞒火工品用途，审核把关不严。

五是矿井用工管理混乱，采掘作业地点承包给不具备资质和能力的施工队伍，不签订书面的劳务承包协议，未交纳工伤保险等，人员位置监测系统形同虚设。

六是峰岩集团安全管理流于形式，安全生产主体责任落空。

七是地方安全监管部门对二亩沟煤矿违规开采煤柱等重大隐患和突出问题检查不力，甚至视而不见、有意回避。

## 浙江海宁龙洲印染有限责任公司“12·3”重大污水罐体坍塌事故

### 事故概况

2019年12月3日，浙江省嘉兴海宁市许村镇荡湾工业园区内海宁市龙洲印染有限责任公司（以下简称龙洲公司）发生污水罐体倒塌，砸中邻近海宁市都彩纺织有限公司、海宁市亿隆纺织有限公司部分车间，罐体内大量污水向厂房内倾泄，造成部分厂房倒塌，造成10人死亡、3人重伤。发生原因是，企业事故污水罐的设计存在缺陷、罐壁钢板材料不符合标准要求、罐体施工过程中焊接质量存在严重问题，污水渗入焊缝未焊透区域，发生氧化腐蚀，使其强度持续减弱，导致焊缝处在水的静压力下发生破裂，进而罐体发生坍塌。

### 主要教训

一是事故企业安全主体责任不落实，将技改项目发包给无设计资质的设计单位、无施工资质的施工单位，工程建设过程中未按规定聘请监理公司对施工过程进行监理。

二是事故企业安全意识薄弱，未识别技改项目带来新的安全风险，对污水存储设施存在的安全隐患视而不见，设施一直带病运转。

三是地方政府及有关职能部门在对企业环保建设项目“三同时”审查过程中，未依照相关法律法规和有关要求，认真组织开展备案、验收、监督、检查等工作。

## 湖南长沙浏阳碧溪烟花制造有限公司“12·4”重大爆炸事故

### 事故概况

2019年12月4日，湖南省浏阳市碧溪烟花制造有限公司石下工区发生爆炸事故，造成13人死亡、13人受伤住院治疗。发生原因是，据初步调查，爆炸发生在石下工区包装作业区域，事发时大量工人正在11、12、13号包装工房（危险等级为1.3级）进行包装作业。据视频和技术分析，引发事故的直接原因是，工人搬运半成品时，半成品与盛装工具摩擦着火，继而引发包装工房内堆放的成品、半成品燃烧、爆炸。由于产品超大规格、超大药量（超GB10631规定的爆竹最大允许药量20倍以上），成品、半成品能整体爆炸，且作业现场严重超人员、超药量，导致群死群伤。

### 主要教训

一是企业存在多股东各自组织生产、分包转包生产工位、超许可范围生产违禁产品和作业现场超核定药量和人员等严重违法违规问题。

二是企业长期以出口为名生产不符合我国强制性国家标准的超标违禁产品，出口环节安全监管存在漏洞，超标违禁产品出口“一路绿灯”。

三是事故发生后，当地隐瞒死亡人数，性质恶劣，影响极坏。

四是属地安全监管责任不落实，未能及时发现并制止企业违法违规行为。目前，国务院安委会已对事故查处进行挂牌督办，湖南省人民政府事故调查组正在对该事故进行调查。相关详细情况待事故结案后将向社会公布。

