--- 
title: "2020年全国应急救援、生产安全事故各十大典型案例"
author: "中华人民共和国应急管理部"
date: "2021-01-05"
output:
  word_document: default
  pdf_document: default
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
geometry:
- b5paper
- tmargin=2.5cm
- bmargin=2.5cm
- lmargin=3.5cm
- rmargin=2.5cm
site: bookdown::bookdown_site
description: 一个简单的中文书示例。
github-repo: yihui/bookdown-chinese
documentclass: ctexbook
---

```{r setup, include=FALSE}
options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 55, digits = 4
)

# 填上你需要用到的包，如 c('ggplot2', 'dplyr')
lapply(c('tidyverse','readxl'), function(pkg) {
  if (system.file(package = pkg) == '') install.packages(pkg)
})
```

2020年是党和国家事业发展历程中极不平凡的一年，也是应急管理工作面临重大风险挑战、取得显著成效的一年。在以习近平同志为核心的党中央坚强领导下，全国各级应急管理部门和国家综合性消防救援队伍忠实践行“对党忠诚、纪律严明、赴汤蹈火、竭诚为民”的训词精神，始终坚持人民至上、生命至上，危急时刻逆向而行、勇往直前，抗疫情、战洪水、化危机，始终奋战在党和人民最需要的地方，有效应对了一系列重特大灾害事故。在各级党委政府坚强领导下和各部门各单位共同努力下，取得了历年来生产安全事故起数和死亡人数最少、自然灾害因灾死亡人数最少的成效。

日前，应急管理部会同国务院安委会办公室、国家减灾委办公室对2020年各类突发灾害事故案例进行梳理，公布了应急救援、生产安全事故各十大典型案例，认真总结应急救援和现场处置的成功经验，推动各地区、各部门、各企业深刻吸取有关事故教训，统筹发展和安全，树牢安全发展理念，压紧压实安全责任，提升全社会应急意识、安全意识和责任意识，筑牢防灾减灾救灾的人民防线。

# 2020年全国应急救援十大典型案例

## 重庆市渝北区加州花园小区居民楼火灾扑救

2020年１月1日16时55分，重庆市渝北区加州花园小区A4幢居民楼（共30层）2层阳台发生火灾，火势蔓延至30层阳台并窜至部分居民室内，造成多人被困。火情发生后，迅速成立现场指挥部，组织救援处置工作。重庆市消防救援总队迅速调派42辆消防车、250余名指战员到场处置。现场指挥部坚持“救人第一、科学施救”，确定“灭救同步”的作战方案，采取“分区攻坚，逐户清理”的措施，组织攻坚力量全力搜救疏散被困群众，全力堵截火势蔓延扩大，明火于1月1日20时许被扑灭。经过全力扑救，安全营救被困群众68人、疏散200余人，火灾未造成人员伤亡。

**主要经验:**按照高层建筑火灾扑救编成，精准调派高层建筑灭火救援专业队到场处置。首战力量到场迅速，充分利用建筑内部固定消防设施，第一时间组织攻坚力量深入建筑内部救人灭火。采取“内攻近战、内外结合、上下合击、逐层消灭”的战术措施，分层疏散被困群众，有效控制火势蔓延。

## 青海省西宁市城中区公交车站路面塌陷救援

2020年１月13日17时24分许，青海省西宁市城中区南大街红十字医院公交车站一辆17路公交车进站上下乘客时，路面突然塌陷，致使公交车和车站部分人员坠落。公交车在下坠过程中砸断地下自来水供水管，水流冲击导致塌陷区快速下陷，造成二次塌陷，又有部分人员坠落。当地迅速调集应急、消防、公安、城管、交通、人防、矿山救援队等专兼职救援力量1000余人进行救援。青海省消防救援总队调派27辆消防车、129名指战员到场处置，利用生命探测仪搜寻、热成像定位、无人机侦察等装备器材搜寻被困人员，采取稳固支撑与开辟救援空间、人工搜寻与工程清障、持续搜救与交替换防相结合的方式，全力搜救被困人员。经过88小时不间断搜救，共营救被困人员22人，找到9名遇难者遗体。

**主要经验:**迅速启动应急响应机制，第一时间成立了现场应急管理处置组，多部门协同，对事故区域采取停气停水停电措施，采用先进适用技术装备，调用不同类型救援队伍协同作战，并得到了社会各公益团队志愿者的支援，救援过程科学有力有序。

## 福建省泉州市欣佳酒店“3·7”重大坍塌事故救援

2020年３月7日19时14分，福建省泉州市鲤城区欣佳酒店所在建筑物发生坍塌，造成71人被困。事故发生后，应急管理部立即启动应急响应，会同住房和城乡建设部等部门派出工作组连夜赶赴现场指导协助应急处置工作。福建省、泉州市迅速组织力量开展救援。国家综合性消防救援队伍、国家安全生产专业救援队伍、中交集团、地方专业队伍、社会救援力量等共计118支队伍、5176人参与抢险救援。福建省消防救援总队迅速调派10个支队的重、轻型救援队1086名指战员，携带生命探测仪、搜救犬以及特种救援装备到场处置。救援人员采取多种方式反复侦查，确定被困人员方位，按照“由表及里、先易后难”的顺序，合理使用破拆、撑顶、剪切等方式破拆建筑构件，多点作业、逐步推进，全力搜寻营救被困人员。卫健部门调派56名专家赶赴泉州支援伤员救治，并在事故现场设立医疗救治点，调配125名医务人员、20部救护车驻守现场，及时开展现场医疗处置、救治和疫情防控工作。经过112小时的艰苦奋战，成功将71名被困人员全部救出，其中42人生还。

**主要经验:**迅速启动重大灾害事故响应机制，第一时间成建制、模块化调集消防救援专业力量到场实施救援。通过“以房找人、以人找人、以物找人”等方法迅速定位，采取“纵横结合、两侧并进”掘进方法，开展地毯式搜寻。针对被埋压人员不同区域位置，采取“搜救犬和生命探测仪交叉搜寻定位、工程机械逐层剥离表层构件”的战术措施，发挥专业装备优势。公安、住建、卫健、疾控、电力、通信和武警部队等部门协同配合，为现场救援行动提供有力保障。

## 湖南省郴州市列车脱轨侧翻事故救援

2020年３月30日11时40分，受连日降雨影响，湖南省郴州市永兴县境内京广线马田墟至栖凤渡站下行K1855+778处发生塌方，T179次（济南-广州）旅客列车行驶至该处时撞上滑塌体脱轨。机车及机后第1至8位车辆脱轨，其中机后第１位脱轨颠覆起火。事故发生后，交通运输部、国家铁路局、应急管理部、国铁集团等组成联合工作组赶赴现场，指导开展应急处置工作。当地迅速组织消防救援队伍147名指战员、28辆消防车和铁路救援力量到场处置。救援人员成立2个灭火攻坚组、4个破拆救人组，迅速出枪灭火，及时疏散抢救人员，对每节车厢进行三轮搜救。经过全力奋战，搜救和疏散128名人员，妥善转运525名旅客，明火于3月30日13时50分被扑灭，铁路于3月31日9时48分恢复运行。

**主要经验:**迅速启动应急响应机制，第一时间调集联动部门赶往现场处置。针对现场火势发展和人员被困情况，及时组织开展救人、破拆和灭火行动，全力营救被困人员，有效扑灭火灾。各救援力量按照救人控火、伤员救治、铁路排险等重点救援任务，各司其职、分工协作，提高了综合救援能力。

## 山西省大同市同煤集团塔山煤矿冒顶事故救援

2020年4月14日14时45分，山西省大同市同煤集团塔山煤矿井下2205巷距工作面30米处发生冒顶事故，掘进工作面当班13人，8人安全升井，5人被困。事故发生后，救援处置工作立即展开，国家矿山应急救援大同队105人及其他专业力量投入救援。经过近30小时不间断全力施救，5名被困人员于4月15日20时35分全部安全升井。

**主要经验:**坚持科学决策、安全救援，冒落区外围区域采取了锁口支护、液压支护等有效措施控制冒落区域扩大，为成功救援提供了安全保障。坚持以人为本、生命至上，现场打钻孔与被困人员进行联系，从心理上和身体上保证被困人员健康状况良好。坚持科技支撑、综合施策，合理运用新技术实施救援，利用高分子材料马丽散对通道上方的煤岩进行了有效固化，确保了救援通道的安全。

## 西藏自治区林芝市巴宜区森林火灾扑救

2020年4月14日17时35分，西藏自治区林芝市巴宜区尼西村附近发生森林火灾，林内腐殖质达10至20厘米，极易燃烧，严重威胁附近村庄和民用炸药库安全。火情发生后，应急管理部持续调度指导灭火工作，并紧急调派西藏森林消防总队400人赴火场参加扑救。西藏自治区党委、政府负责同志赶赴现场组织救援处置工作。前线指挥部认真研判分析火场态势，实施扑打清理和开设隔离带相结合的战术，采取“控线、灭点、清中间”的战法迅速控制火势，综合利用以水灭火、人工作业等多种技术手段打歼灭战，跟进开展余火清理，强化后勤保障。扑打火线14公里，清理烟点6400余处、站杆倒木3900余根，开设防火隔离带3.5公里，实施了两次人工增雨。经过森林消防队伍、消防救援队伍、公安、当地武警官兵、民兵和地方干部群众等2000余人历时4昼夜持续扑救，明火于4月18日17时全部扑灭，受威胁的389名群众全部安全转移，所有民爆物品全部安全转运。

**主要经验:**快速响应靠前指挥，迅速启动应急响应机制，森林消防指战员第一时间奔赴火场。前方指挥部科学研判、果断决策，森林消防队伍在消防救援队伍、武警等力量协同配合下，融合运用多种战法，泵车结合、以水灭火，打隔结合、重点封控，成功将明火扑灭。预警及时安全托底，火场风力风向变化无常，灭火安全员第一时间发出险情预警，一线指挥员反应迅速、处置得当，组织人员快速转移至预设安全区域成功避险，确保了人身安全。

## 沈海高速浙江温岭段“6·13”液化石油气运输槽罐车重大爆炸事故救援

2020年６月13日16时41分许，沈海高速浙江台州温岭出口处，一辆载有25.36吨液化石油气、由宁波开往温州的槽罐车发生爆炸，爆炸波及范围半径约400至500米，造成一栋民房局部和两处厂房倒塌，600余间房屋和多辆汽车受损，多人伤亡并有人员在事故中失联。事故发生后，应急管理部立即启动应急响应，迅速调集7支重型救援队、3支轻型救援队，共100辆消防车、547名指战员，携带专业搜救设备和6头搜救犬开展搜救。浙江省委、省政府负责同志赶赴现场组织救援处置工作，调动中交集团90余人、挖掘机4台投入救援。现场救援共投入大型抢险救援设备30多台（套），出动各类救援车辆151辆、医疗救护车38辆、参与救援人员2600多人次。面对事故现场二次坍塌、二次爆炸等次生灾害叠加的风险，救援人员将爆炸现场划分为坍塌厂房区、受损居民区和槽罐车撕裂抛洒区，实施交叉轮流搜救。经过38个小时的全力搜救，事故中175名伤员全部获救，所有失联人员全部找到并确认身份。

**主要经验:**按照应急预案一次性调足重、轻型搜救编队和专业装备到场开展救援，集中力量打通救援通道。针对失联人数确定难、人员深度埋压定位难的实际，协调公安等部门全方位搜集受灾区域人口户籍、手机信号、人物特征、亲属关联等有效数据信息，确定被困群众人数和被埋压区域。救援力量抢时间、抓战机，昼夜不歇、协同配合，为营救人员赢得了宝贵时间。

## 安徽省阜阳市颍上县姜唐湖蓄洪区戴家湖涵闸重大险情处置

2020年７月26日9时57分，安徽省阜阳市颍上县姜唐湖行蓄洪区戴家湖涵闸因闸门破损导致洪水外溢，严重威胁戴家湖内8000余名群众生命安全。险情发生后，国家防总立即派出应急管理部、水利部等部门组成的工作组紧急赶赴现场协助抢险救援，并持续跟踪调度、强化协调。安徽省、阜阳市立即组织戴家湖区域内的群众转移。共出动解放军、消防救援队伍、森林消防队伍、中国铁建、中国电建、中国能建、干部群众等抢险人员3487人，以及挖掘机95台、推土机58台、自卸车96台，采取封堵涵闸出水口、构筑“养水盆”、填筑防洪闸侧月牙堤等应急处置措施，全面开展抢险救援。经过持续6天的紧急抢险，涵闸于8月1日上午彻底封堵，安全转移8476名受威胁群众，成功解除了险情。

**主要经验:**各救援力量模块化调派、成建制集结，快速响应投入战斗。针对受灾群众点多面广、水流复杂的实际，采取舟艇编队行进和无人机空中侦察相结合的方式，全力营救疏散被困人员。整合人员装备，设置排险、清灌、除草、清理、安全等作战小组，梯次作战、立体推进，及时清除堤坝灌木草丛。充分发挥卫星便携站、单兵图传、动中通移动指挥车等侦察、通信作用，确保科学精准救援。

## 山西省临汾市聚仙饭店“8·29”重大坍塌事故救援

2020年８月29日9时40分许，山西省临汾市襄汾县陶寺乡陈庄村聚仙饭店发生坍塌，造成数十人被困。事故发生后，应急管理部、住房和城乡建设部等部门立即派出联合工作组赶赴现场指导处置工作。山西省、临汾市迅速组织应急、消防、公安、卫健、人武及相关救援人员900余人，出动大型救援装备车辆20余辆、救护车15辆，全力搜救被困人员。经过18个小时持续救援，先后从废墟中搜救出57名被困人员，其中28人生还。

**主要经验:**联勤联动响应迅速，第一时间调集各有关力量到场实施救援。现场指挥部科学评估、精准施救，分阶段、分区域、分人员制定救援方案，采取搜救犬与仪器、人工与机械配合作业的搜救方式，全力营救被困人员。蓝天、天龙、晋煤救援队等多方社会力量协同救援，为救援行动提供有效的人员、技术和装备保障。

## 湖南省怀化市沪昆高速雪峰山隧道火灾扑救

2020年10月25日1时53分，沪昆高速湖南怀化境内雪峰山隧道K1376+600处，一辆装载电动自行车的半挂车起火，造成33辆车滞留，大量人员被困在隧道内。事故发生后，国家相关部门迅速部署事故抢险救援、人员疏散、风险防范等工作。湖南省、邵阳市立即组织应急、公安、交通等有关方面开展救援处置工作。湖南省消防救援总队迅速调派6个支队238名指战员，以及消防机器人、大功率水罐车、排烟车等56台（辆）专业设备现场处置，采取固移结合、排烟散热、梯次推进、分段灭火等战术措施进行救援，明火于10月25日18时23分被扑灭。经过全力抢险救援，营救疏散隧道内司乘人员65人。

**主要经验:**迅速启动应急响应机制，一次性调派足够力量，第一时间疏散隧道内滞留人员，及时在隧道上风方向利用排烟车交替正压送风排烟，组成多个攻坚小组深入隧道内部分段实施灭火作业，为打通道路争取了时间。公安、高速集团、隧道管理、货运公司等部门和单位快速响应，协同配合，各司其职，提高了综合救援能力。

# 2020年全国生产安全事故十大典型案例

## 福建泉州欣佳酒店“3·7”重大坍塌事故

### 事故概况

2020年3月7日19时14分，福建省泉州市鲤城区欣佳酒店所在建筑物发生坍塌事故，造成29人死亡、42人受伤，直接经济损失5794万元。发生原因是，事故单位将欣佳酒店建筑物由原四层违法增加夹层改建成七层，达到极限承载能力并处于坍塌临界状态，加之事发前对底层支承钢柱违规加固焊接作业引发钢柱失稳破坏，导致建筑物整体坍塌。

### 主要教训

**一是企业违法违规肆意妄为。**欣佳酒店的不法业主在未取得建设相关许可手续，且未组织勘察、设计的情况下，多次违法将工程发包给无资质施工人员，在明知楼上有大量人员住宿的情况下违规冒险蛮干，最终导致建筑物坍塌；相关中介服务机构违规承接业务甚至出具虚假报告。

**二是安全发展理念不牢。**鲤城区片面追求经济发展，通过“特殊情况建房”政策为违法建设开绿灯，埋下重大安全隐患；福建省有关部门及泉州市对违法建筑长期大量存在的重大安全风险认识不足，房屋安全隐患排查治理流于形式。

**三是地方政府有关部门监管执法严重不负责任。**泉州市、鲤城区的规划、住建、城管、公安等部门对欣佳酒店未取得建设相关许可手续、未取得特种行业许可证对外营业等违法违规行为长期视而不见。

**四是相关部门审批把关层层失守。**泉州市、鲤城区消防机构、公安等有关部门及常泰街道在材料形式审查和现场审查中把关不严，使不符合要求的项目蒙混过关、长期存在。

## 沈海高速浙江温岭段“6·13”液化石油气运输槽罐车重大爆炸事故

### 事故概况

2020年6月13日16时41分许，浙江省台州市温岭市境内沈海高速公路温岭段温岭西出口下匝道发生一起液化石油气运输槽罐车重大爆炸事故，共造成20人死亡，175人受伤，直接经济损失9470余万元。发生原因是，事故车辆行驶至弯道路段时，未及时减速导致车辆发生侧翻，罐体前封头与跨线桥混凝土护栏端头猛烈撞击，形成破口并快速撕裂、解体，导致液化石油气迅速泄出、汽化、扩散，遇过往机动车火花产生爆燃，最后发生蒸汽云爆炸。

### 主要教训

**一是企业安全生产主体责任严重不落实。**瑞安市瑞阳危险品运输有限公司无视国家有关危化品运输的法律法规，未严格开展GPS动态监控、安全教育管理、如实上传电子路单等工作，存在车辆挂靠经营等违规行为，GPS监管平台运营服务商违规协助企业逃避监管。

**二是有关行业协会未如实开展安全生产标准化建设等级评定工作。**未发现企业自评报告弄虚作假、监控人员配备不符合规定等问题，违规发放安全生产标准化建设等级证明，违规将年度核查评定为合格。

**三是事故路段匝道业主、施工、监理等单位在防撞护栏施工过程中未严格履行各自职责，防撞护栏搭接施工不符合标准规范和设计文件要求。**

**四是有关地方党委政府安全发展理念树立不牢固，安全生产领导责任落实不到位。**地方政府交通运输、公安、公路管理等部门，对危化品运输、公路建设养护、工程质量监督等方面安全风险管控和监管执法存在漏洞。

## 湖北仙桃蓝化有机硅有限公司“8·3”较大闪爆事故

### 事故概况

2020年8月3日17时39分许，湖北省仙桃市西流河镇仙桃市蓝化有机硅有限公司甲基三丁酮肟基硅烷车间发生爆炸事故，造成6人死亡、4人受伤。发生原因是，操作工在清理分层器内物料时，没有彻底将分层器底部物料排放至萃取工序，导致超量的丁酮肟盐酸盐进入产品中和工序、放入1#静置槽，致使“反应下移”，反应热量在静置槽中累积，静置槽没有温度监测及降温措施，丁酮肟盐酸盐发生分解爆炸。

### 主要教训

**一是事故企业安全意识淡薄、法治意识缺失。**事故车间未经正规设计和验收，违法组织生产，未制定分层器工序操作规程；安全风险辨识不到位，对丁酮肟盐酸盐危险特性认识不足；设备设施部件和自动控制系统存在缺陷，从业人员学历资格达不到要求，对异常工况处理不当。

**二是地方政府安全发展红线意识不强。**履行安全生产属地管理责任不到位，对事故企业违法组织生产监督检查不力，全面摸排安全风险和事故隐患工作不彻底。

## 山西临汾聚仙饭店“8·29”重大坍塌事故

### 事故概况

2020年8月29日9时40分许，山西省临汾市襄汾县陶寺乡陈庄村聚仙饭店发生坍塌事故，造成29人死亡、28人受伤，直接经济损失1164.35万元。发生原因是，聚仙饭店建筑结构整体性差，经多次加建后，宴会厅东北角承重砖柱长期处于高应力状态；北楼二层部分屋面预制板长期处于超荷载状态，在其上部高炉水渣保温层的持续压力下，发生脆性断裂，形成对宴会厅顶板的猛烈冲击，导致东北角承重砖柱崩塌，最终造成北楼二层南半部分和宴会厅整体坍塌。

### 主要教训

一是聚仙饭店经营者长期违法占地，多次通过不正当手段取得未经审批的集体土地建设用地使用证，拒不执行原襄汾县国土资源等部门的行政处罚和人民法院的裁定。

二是聚仙饭店经营者先后8次违规扩建，从未经过专业设计、无资质且不按规范施工，也从未经过竣工验收，仅依靠包工头和个人想法，建设全程无人管无人查，房屋质量安全无保障。

三是聚仙饭店经营者擅自将自建农房从事经营活动，未对建筑安全隐患排查整治，安全生产主体责任不落实。

四是襄汾县陶寺乡政府和陈庄村“两委”未认真履行属地管理职责，对农村自建房改为经营活动场所的管控缺失，未按要求对擅自改建扩建加层、野蛮装修和违法违规建房等进行重点排查整治。

五是临汾市襄汾县政府及有关部门行政审批和监管执法不严，违规将加盖政府公章的空白集体土地建设用地使用证提前发给各乡镇，违规对过期证照办理延期；在政府开展的多轮打击违法占地、非农建设整治等行动中，监管执法人员均未对该饭店长期的违法违规行为予以有效制止查处。

## 甘肃白银甘肃宏达铝型材有限公司“9·6”较大生产安全事故

### 事故概况

2020年9月6日2时22分许，甘肃省白银市白银区甘肃宏达铝型材有限公司熔铸车间发生一起冷却水闪蒸事故，造成4人死亡，6人受伤。发生原因是，熔铸车间作业工人发现铸造过程出现异常情况后，在采取加铝饼、调速等降温方法效果不明显时，未及时终止作业，导致铝合金棒拉漏，大量高温铝液进入冷却竖井，冷却水瞬间汽化并发生剧烈的铝粉氧化反应，产生的混合气体体积在相对密闭空间急剧膨胀，聚集的能量突然释放形成冲击波，导致事故发生。

### 主要教训

**一是企业安全制度落实不到位、内容不科学。**安全培训制度未落实，三项岗位人员持证不足，三级安全培训教育不到位；违法采用12小时两班连续工作制度，熔铸车间安全管理缺失；工作制度不合理导致夜班生产作业调度不畅、安全监管失位，当班班长发现现场违规问题纠正不及时，对生产过程中出现的异常状况处置失当。

**二是企业安全管理不到位。**熔铸车间风险等级与安全管理措施不匹配，隐患排查治理未闭环；制定的熔铸工安全操作规程缺少具体操作程序和步骤、岗位主要危险有害因素等；安全管理机构设置不健全，安全管理职责边界不清，安全管理人员数量不足。

**三是监管部门安全检查专业力量不足，未能及时发现熔铸车间铸造过程中的安全隐患和存在的问题。**

## 渤海海峡老铁山水道“9·18”重大水上交通事故

### 事故概况

2020年9月18日4时19分许，渤海海峡老铁山水道发生一起商船与渔船碰撞的重大水上交通事故，造成渔船沉没，渔船船员10人全部失踪，直接经济损失约300万元。发生原因是，渔船违反避碰规则，外籍商船未能采取安全航速航行，两船会遇构成紧迫局面后，均未采取有效的避碰行动，最终发生碰撞。

### 主要教训

一是渔船船员安全意识不高，安全技能不足，在事故中未履行避让义务。

二是渔船自动识别系统不能正常工作，致使无法在商船的电子海图系统上显示本船位置和动态。

三是商船过度依赖自动驾驶设施设备，忽略对雷达、视觉等其他有效瞭望手段的使用，导致未能及时识别和发现渔船。

四是商船在事故发生后离开现场，未能第一时间救助遇险渔民，扩大了事故损失。

五是渔港源头监管不到位，未能对出港作业渔船实施有效检查，致使渔船配员不符合法定要求。

## 重庆能投渝新能源有限公司松藻煤矿“9·27”重大火灾事故

### 事故概况

2020年9月27日0时20分，重庆能投渝新能源有限公司松藻煤矿发生重大火灾事故，造成16人死亡、42人受伤，直接经济损失2501万元。发生原因是，松藻煤矿二号大倾角运煤上山胶带下方煤矸堆积，起火点63.3米标高处回程托辊被卡死、磨穿形成破口，内部沉积粉煤；磨损严重的胶带与起火点回程托辊滑动摩擦产生高温和火星，点燃回程托辊破口内积存粉煤；胶带输送机运转监护工发现胶带异常情况，电话通知地面集控中心停止胶带运行，紧急停机后静止的胶带被引燃，胶带阻燃性能不合格、巷道倾角大、上行通风，火势增强，引起胶带和煤混合燃烧；火灾烧毁设备，破坏通风设施，产生的有毒有害高温烟气快速蔓延至2324-1采煤工作面，造成重大人员伤亡。

### 主要教训

**一是松藻煤矿重效益轻安全。**该矿职工已经检查出二号大倾角胶带巷浮煤多，下托辊、上托架损坏变形严重等问题和隐患，并向煤矿矿长等管理人员进行了报告，但该矿矿长毫无“红线”意识，为不影响矿井正常生产未立即停产，而是计划在国庆节停产检修期间更换，并要求整治工作不能影响胶带运煤，让胶带运输机“带病运行”。

**二是矿井安全管理混乱。**二号大倾角运煤上山胶带防止煤矸洒落的挡矸棚维护不及时，变形损坏，皮带运行中洒煤严重，皮带下部煤矸堆积多、掩埋甚至卡死下托辊，少数下托辊被磨平、磨穿，已磨损严重的皮带与卡死的下托辊滑动摩擦起火；煤矿没有按规定统一管理、发放自救器，有的自救器压力不够。

**三是重庆能源集团督促煤矿安全生产管理责任落实不到位，对所属煤矿安全实行四级管理，职能交叉、职责不清，责任落实层层弱化。**

## 山西太原台骀山滑世界农林生态游乐园有限公司“10·1”重大火灾事故

### 事故概况

2020年10月1日13时许，山西省太原市迎泽区小山沟村台骀山景区冰雕馆发生一起重大火灾事故，造成13人死亡、15人受伤。发生原因是，当日景区10kV供电系统故障维修结束恢复供电后，景区电工在将自备发电机供电切换至市电供电时，进行了违章带负荷快速拉、合隔离开关操作，在照明线路上形成的冲击过电压击穿装饰灯具的电子元件造成短路；火车通道内照明电气线路设计、安装不规范，采用的无漏电保护功能大容量空气开关无法在短路发生后及时跳闸切除故障，持续的短路电流造成电子元件装置起火，引燃线路绝缘层及聚氨酯保温材料，进而引燃聚苯乙烯泡沫夹芯板隔墙及冰雕馆内的聚氨酯保温材料。

### 主要教训 

一是企业无视国家法律法规和政策规定，在未取得有关部门行政审批手续的情况下，长期进行违法占地、违法建设等活动。

二是企业在游乐场馆建设中没有使用正规的设计、施工、监理、验收单位进行建设，致使电气线路敷设、接地短路保护和逃生通道、安全出口的设置等不符合安全要求，甚至人为封堵冰雕馆安全出口。

三是企业违规在人员密集场所使用聚氨酯、聚苯乙烯等易燃可燃保温材料。

四是企业负责人安全意识淡薄，未建立安全生产管理机构、配备专兼职安全管理人员、健全全员安全生产责任制，安全隐患排查、整治、整改走过场，安全管理流于形式。

五是地方政府没有正确处理安全与发展的关系，有关部门安全监管责任不落实。

## 湖南衡阳源江山煤矿“11·29”重大透水事故

### 事故概况

2020年11月29日11时30分，湖南省衡阳市耒阳市导子煤业有限公司源江山煤矿发生重大透水事故，造成5人死亡、8人失联，直接经济损失3484.03万元。发生原因是，源江山煤矿超深越界在-500m水平61煤一上山巷道式开采急倾斜煤层，在矿压和上部水压共同作用下发生抽冒，导通上部导子二矿-350m至-410m采空区积水，大量老空积水迅速溃入源江山煤矿-500m水平，并迅速上升稳定至-465m，导致井巷被淹，造成重大人员伤亡。

### 主要教训

**一是源江山煤矿长期超深越界，盗采国家资源。**该矿2011年以前就已经越界开采，2019年底就超深越界至-500m水平；通过篡改巷道真实标高、不在图纸上标注、井下设置活动铁门密闭、不安装监控系统和人员定位系统等方式逃避安全监管，长期盗采国家资源。

**二是源江山煤矿违法组织生产。**该矿在安全生产许可证注销、地方政府下达停产指令、等待技改期间，擅自拆除提升绞车和入井钢轨封条、切断主井井口视频监控电源，昼停夜开，仅2020年就生产出煤5.56万吨。

**三是源江山煤矿使用国家明令禁止的工艺，以包代管，生产组织混乱。**该矿采用巷道式采煤，坑木支护，采掘布局混乱，多头作业，通风系统不健全，未形成2个安全出口，有的采煤工作面使用压风管路通风；将井下采掘作业承包给多个私人包工队，以包代管，仅事故区域就有3个包工队。

**四是源江山煤矿在老空水淹区域下违规开采急倾斜煤层。**该矿在-500m水平61煤采掘期间，明知工作面上方采空区存在积水，仍然心怀侥幸，冒险蛮干，在老空水淹没区域下违规开采急倾斜煤层。

**五是源江山煤矿违规申领火工品且管理混乱。**该矿明知其属于停工停产待建矿井，多次借整改之名违规向耒阳市公安局民爆大队申领火工品；在公安机关清缴火工品期间，擅自拆除民爆物品仓库封条，使用火工品组织生产，并采取多领少用的方式，违规处置剩余火工品。

## 重庆永川吊水洞煤业有限公司“12·4”重大火灾事故

### 事故概况

2020年12月4日17时17分，重庆市胜杰再生资源回收有限公司（以下简称胜杰回收公司）在重庆市永川区吊水洞煤业有限公司（以下简称吊水洞煤矿）回收设备时发生重大火灾事故，造成23人死亡、1人重伤，直接经济损失2632万元。发生原因是，胜杰回收公司在吊水洞煤矿井下回撤作业时，回撤人员在-85m水泵硐室内违规使用氧气/液化石油气切割2#、3#水泵吸水管，掉落的高温熔渣引燃了水仓吸水井内沉积的油垢，油垢和岩层渗出油燃烧产生大量有毒有害烟气，在火风压作用下蔓延至进风巷，造成人员伤亡。

### 主要教训

一是吊水洞煤矿未按上报的回撤方案组织回撤作业。上报给地方政府和有关部门的撤出井下设备报告及回撤方案中，隐瞒了已将井下回撤工作交由胜杰回收公司组织实施的事实，且上报的回撤方案中未将井下水泵列入回撤设备清单，但实际对水泵进行了回撤。

二是胜杰回收公司不具备煤矿井下作业资质，井下设备回撤作业现场管理混乱，安排未取得焊接与热切割作业证的人员在井下进行切割作业，在-85m水泵硐室气割水管前，未采取措施清理或者隔离焊碴、防止飞溅掉落到存有岩层渗出油的吸水井的措施。

三是吊水洞煤矿和胜杰回收公司安全管理混乱。未落实煤矿入井检身制度，入井人员未随身携带自救器，隐患排查治理不到位。

