--- 
title: "2020年全国十大自然灾害"
author: "中华人民共和国应急管理部"
date: "2021-01-02"
output:
  word_document: default
  pdf_document: default
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
geometry:
- b5paper
- tmargin=2.5cm
- bmargin=2.5cm
- lmargin=3.5cm
- rmargin=2.5cm
site: bookdown::bookdown_site
description: 一个简单的中文书示例。
github-repo: yihui/bookdown-chinese
documentclass: ctexbook
---

```{r setup, include=FALSE}
options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 55, digits = 4
)

# 填上你需要用到的包，如 c('ggplot2', 'dplyr')
lapply(c('tidyverse','readxl'), function(pkg) {
  if (system.file(package = pkg) == '') install.packages(pkg)
})
```

2020年，我国气候年景偏差，主汛期南方地区遭遇1998年以来最重汛情，自然灾害以洪涝、地质灾害、风雹、台风灾害为主，地震、干旱、低温冷冻、雪灾、森林草原火灾等灾害也有不同程度发生，经应急管理部会同工业和信息化部、自然资源部、住房城乡建设部、交通运输部、水利部、农业农村部、卫生健康委、统计局、气象局、银保监会、粮储局、中央军委联合参谋部和政治工作部、红十字会总会、国铁集团等国家减灾委成员单位会商核定，全年各种自然灾害共造成1.38亿人次受灾，591人死亡失踪，10万间房屋倒塌，176万间房屋损坏，农作物受灾面积19957.7千公顷，直接经济损失3701.5亿元。与近5年均值相比，2020年全国因灾死亡失踪人数下降43%，其中因洪涝灾害死亡失踪279人、下降53%，均为历史新低。2020年全国十大自然灾害如下：

# 2020年全国十大自然灾害

## 7月份长江淮河流域特大暴雨洪涝灾害

7月份，长江、淮河流域连续遭遇5轮强降雨袭击，长江流域平均降雨量（259.6毫米）较常年同期偏多58.8%，为1961年以来同期最多，长江发生3次编号洪水；淮河流域平均降雨量（256.5毫米）较常年同期偏多33%。受强降雨影响，淮河流域江河来水偏多1.5-2倍、长江中下游流域偏多4-6成，引发严重洪涝灾害。灾害造成安徽、江西、湖北、湖南、浙江、江苏、山东、河南、重庆、四川、贵州11省（市）3417.3万人受灾，99人死亡，8人失踪，299.8万人紧急转移安置，144.8万人需紧急生活救助；3.6万间房屋倒塌，42.2万间不同程度损坏；农作物受灾面积3579.8千公顷，其中绝收893.9千公顷；直接经济损失1322亿元。

## 8月中旬川渝及陕甘滇严重暴雨洪涝灾害

8月10-17日，西南地区东部、四川盆地至陕西、甘肃等地连续出现多轮强降雨过程。其中，四川盆地中西部和甘肃南部降水量较常年同期偏多2到4倍，陕西西南部及云南偏多五成。强降雨引发长江上游发生特大洪水，三峡水库出现建库以来最大入库流量75000立方米每秒，多地暴发山洪、泥石流等灾害。灾害造成四川、重庆、陕西、甘肃、云南5省（市）53市（州）852.3万人受灾，58人死亡，13人失踪，107.1万人紧急转移安置，8.3万人需紧急生活救助；2.3万间房屋倒塌，35万间不同程度损坏；农作物受灾面积331.1千公顷，其中绝收58.6千公顷；直接经济损失609.3亿元。

## 6月上中旬江南华南等地暴雨洪涝灾害

6月2-14日，江南、华南及贵州等地出现多轮强降雨天气，且降雨落区重叠。其中，6月5-10日，广西东北部、广东中东部等地降雨量达300～500毫米，广东惠州和汕尾局地600～979毫米。受连续强降雨影响，广西西江干流及支流、广东北江中游及支流80余条河流发生超警以上洪水，其中广西柳江支流洛清江、广东北江支流潖江等5条河流发生超历史洪水，引发洪涝及次生地质灾害。灾害造成广东、广西、湖南、贵州、浙江、福建、江西、湖北8省（区）714.4万人受灾，54人死亡，9人失踪，47.5万人紧急转移安置，20.1万人需紧急生活救助；近6700间房屋倒塌，6.6万间不同程度损坏；农作物受灾面积577.5千公顷，其中绝收62.5千公顷；直接经济损失210.6亿元。

## 6月下旬西南等地暴雨洪涝灾害

6月20-28日，重庆、四川、贵州至长江中下游地区遭遇两次降雨过程。其中，20-25日，上述地区累计降雨量超过100毫米的面积达33万平方公里，重庆南川、贵州黄平和惠水、湖南常宁日降雨量达到或突破当地6月历史极值；重庆、四川、贵州等多省共计58条河流发生超警以上洪水，16条河流发生超保洪水，3条中小河流发生超历史洪水，重庆綦江五岔站水位、流量为有资料以来第1位。26-28日，川渝至长江中下游出现新一轮强降雨过程，暴雨区域北移，四川盆地、重庆西南部、贵州北部、湖北东部和西南部、安徽北部、江苏中部等地大部地区相继出现大到暴雨，四川东部、湖北北部、安徽北部等地局地降雨量达250～300毫米。两轮降雨过程引发洪涝灾害，造成四川、贵州、重庆、湖南、安徽、江西、湖北7省（市）597.8万人受灾，36人死亡，3人失踪，24.9万人紧急转移安置，9.9万人需紧急生活救助；4100余间房屋倒塌，4.3万间不同程度损坏；农作物受灾面积438.6千公顷，其中绝收48千公顷；直接经济损失113.7亿元。

## 2020年第4号台风“黑格比”

2020年第4号台风“黑格比”于8月4日凌晨3时30分前后以近巅峰强度在浙江省乐清市沿海登陆，登陆时中心附近最大风力有13级（38m/s）。受其影响，3-5日，浙江温州、台州、金华等地部分地区累计降雨量250～350毫米，温州永嘉和乐清局地达400～552毫米。灾害造成浙江、上海2省（市）5市30个县（市、区）188万人受灾，5人死亡，32.7万人紧急转移安置，1.2万人需紧急生活救助；4300余间房屋倒塌，8000余间不同程度损坏；农作物受灾面积76.3千公顷，其中绝收6.3千公顷；直接经济损失104.6亿元。

## 云南巧家5.0级地震

5月18日21时47分，云南昭通市巧家县（北纬27.18度，东经103.16度）发生5.0级地震，震源深度8公里。地震造成昭通市巧家、鲁甸2县4人死亡（巧家县小河镇2人因房屋倒塌致死、新店镇1人因滚石砸中致死，鲁甸县乐红乡1人因滚石砸中致死），28人受伤（巧家县26人，鲁甸县2人），1151间房屋损坏，直接经济损失1.01亿元。

## 新疆伽师6.4级地震

1月19日21时27分，新疆喀什地区伽师县（北纬39.83度，东经77.21度）发生6.4级地震，震源深度16公里，此后震中附近又相继发生1次5.2级余震和数次4.0级以上余震。地震造成1人死亡、2人轻伤，4000余间房屋不同程度损坏，部分道路、桥梁、水库等设施受损，直接经济损失16.2亿元。

## 东北台风“三连击”

8月下旬至9月上旬，两周内第8号台风“巴威”、第9号台风“美莎克”和第10号台风“海神”先后北上影响东北地区，间隔时间短、影响区域高度重叠，造成东北地区半个月内平均降水量达170.1毫米，较常年同期偏多3倍，为1961年以来历史同期最多。台风带来的降雨造成嫩江、松花江、黑龙江等主要江河长时间超警，大风造成黑龙江、吉林等地玉米等农作物大面积倒伏，直接经济损失128亿元。

## 4月下旬华北西北低温冷冻灾害

4月19-25日，华北、西北出现持续大范围大风降温天气过程，局地伴有沙尘天气，其中河北西北部、北京中西部、内蒙古东南部和中部偏南地区等地8级以上阵风出现时长有24-45小时，内蒙古东南部超过48小时；山西大同市阳高县、云冈区部分地区最低气温降至-9℃。持续大风低温造成大面积坐果期果树冻伤、大棚损毁、蔬菜受冻。灾害造成河北、山西、内蒙古、黑龙江、陕西、甘肃、宁夏7省（区）432.3万人受灾，农作物受灾面积530.1千公顷，其中绝收154.1千公顷，直接经济损失82亿元。

## 云南春夏连旱

2020年入春后，云南持续高温少雨引发严重旱情，其中，普洱南部、西双版纳降水偏少6～8成；3月份全省平均气温达17℃，较常年同期偏高1.5℃，为历史同期第3高，造成部分城市供水紧张、农村人畜饮水困难。4月底，部分地区出现降雨，旱情得到一定程度缓解。5月1-14日，全省再次出现高温少雨天气，全省有96个站点共出现30℃以上高温791站次；累计平均降水量8.8毫米，较常年少75%，旱情再度发展。灾害造成玉溪、昭通、楚雄等16市（州）106个县（市、区）589万人受灾，197.6万人因旱需生活救助，其中156.6万人因旱饮水困难需救助；农作物受灾面积871.7千公顷，其中绝收33.9千公顷；饮水困难大牲畜46.8万头（只）；直接经济损失34.9亿元。

